platform :ios, '11.4'
source 'https://github.com/CocoaPods/Specs.git'

target 'Sixt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HseApp
  pod 'Alamofire', :inhibit_warnings => true
  pod 'SnapKit', :inhibit_warnings => true
  pod 'Kingfisher', :inhibit_warnings => true
  pod 'ProgressHUD', :inhibit_warnings => true

  target 'SixtTests' do
    inherit! :search_paths
    # Pods for testing
  end

#  target 'SixtUITests' do
#    # Pods for testing
#  end

end
